language: r
sudo: required
warnings_are_errors: false

# blacklist
# branches:
#  except:
#    - master

# whitelist
# branches:
#  only:
#    - release

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install jags
#  - sudo apt-get install r-cran-rjags

install: travis_wait 30 mvn install
  
## AJ - this looks like a shortcut to the long version below
# Code coverage
r_packages:
  - covr
  - R2jags
  - rjags
  - MixSIAR

## instructions from http://jtleek.com/protocols/travis_bioc_devel/
#install:
#  - ./travis-tool.sh install_bioc S4Vectors
#  - ./travis-tool.sh install_bioc IRanges
#  - ./travis-tool.sh install_r Matrix
#  - ./travis-tool.sh install_r knitr
#  - ./travis-tool.sh install_r rmarkdown
#  ## For installing all CRAN dependencies using rpack's DESCRIPTION
#  - ./travis-tool.sh install_deps
  
after_success:
- Rscript -e 'library(covr); codecov()'
